version: '3.8'

services:
  msto:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    command: >
      --tickers AAPL MSFT GOOGL
      --mode continuous
      --strategies all
      --log-level INFO
      --interval 300
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-msto_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-msto_pass}
      POSTGRES_DB: ${POSTGRES_DB:-msto_dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msto_user -d msto_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 